return {
    ["apparel"]                                         = { "adorbit" , "flipkart" , "amazon" } ,
    ["apparel/apparel accessories"]                     = { "adorbit" , "flipkart" , "amazon" } ,
    ["apparel/apparel accessories/wedding accessories"] = { "adorbit" , "flipkart" , "amazon" } ,
    ["apparel/apparel accessories/bags"]                = { "adorbit" , "flipkart" , "amazon" } ,
    ["apparel/apparel accessories/belts"]               = { "adorbit" , "flipkart" , "amazon" } ,
    ["apparel/apparel accessories/eyewear"]             = { "adorbit" , "flipkart" , "amazon" } ,
    ["apparel/clothing/shirts"]                         = { "adorbit" , "flipkart" , "amazon" } ,
    ["apparel/clothing/women shirts"]                   = { "adorbit" , "flipkart" , "amazon" } ,
    ["apparel/clothing/sleepwear"]                      = { "adorbit" , "flipkart" , "amazon" } ,
    ["apparel/clothing/suits"]                          = { "adorbit" , "flipkart" , "amazon" } ,
    ["apparel/footwear/roller shoes"]                   = { "adorbit" , "flipkart" , "amazon" } ,
    ["apparel/footwear/sandals"]                        = { "adorbit" , "flipkart" , "amazon" } ,
    ["astrology/horoscope/capricorn"]                   = { "adorbit" , "ganeshaspeaks" } ,
    ["astrology/horoscope/fortune prediction"]          = { "adorbit" , "ganeshaspeaks" } ,
    ["astrology/horoscope/gemini"]                      = { "adorbit" , "ganeshaspeaks" } ,
    ["content/video/sport"]                             = { } ,
    ["content/video/tech"]                              = { "adorbit" } ,
    ["xpl/homescreen/news"]                             = { "newsplus23", "sponsored", "adorbit" },
    ["xpl/homescreen/cerina"]                           = { "newspoint" , "timesnow", "newsplus", "shortpedia" },
    ["xpl/cms/categories"]                              = { "xpl_cms_categories" },
    ["xpl/homescreen/ott"]                              = { "xpl_ott", "serverads"},
    ["xpl/homescreen/memes"]                            = { "xpl_memes", "serverads" }
}